### ISSUE TITLE
Add commit info (author name, desc, title) in status command.

### ISSUE THREAD

**Issue by ArcticEcho** [ArcticEcho/Phamhilator#19]
Based on [Undo's challenge](http://chat.meta.stackexchange.com/transcript/message/2545607#2545607).

**Comment by ArcticEcho** [comment]
Whenever I run this I keep getting a FNF exception, so I'm going to see if GitHub's API can come to the rescue.

**Comment by ProgramFOX** [comment]
FNF? FileNotFound? Weird, worked fine for me. Have you added Git to your PATH?

**Comment by ArcticEcho** [comment]
Yep, it happens every time. And yes, I've added git (although it wasn't easy trying to locate Git's path).

**Comment by ProgramFOX** [comment]
Is there any Git client you use? For me, it works fine, and I just use Git for Windows, no client such as GitHub for Desktop or something.

**Comment by ArcticEcho** [comment]
Right, well I'm using the GitHub for windows client. So...

**Comment by ProgramFOX** [comment]
That *might* make a difference. Does it work if you just use Git for Windows?

**Comment by ArcticEcho** [comment]
Erm, I haven't tried yet.

**Comment by ArcticEcho** [comment]
I'll hopefully have a chance tonight to test it out again.

**Comment by ArcticEcho** [comment]
Erm, well I didn't have time that night to test it out. I'm downloading it now...

**Comment by ArcticEcho** [comment]
Ugh, still not much of an improvement. Atm I'm using this for debugging (obviously I'll change this when the bug's fixed):

    Process p = new Process();
    ProcessStartInfo psi = new ProcessStartInfo();
    psi.FileName = "cmd.exe";
    psi.Arguments = "/c git log --pretty=format:\"[`%h` (%s by %cn)]\" -n 1";
    psi.WorkingDirectory = @"C:\Users\Samuel\Documents\GitHub\Phamhilator";//Directory.GetParent(AppDomain.CurrentDomain.BaseDirectory).FullName;
    psi.UseShellExecute = false;
    psi.RedirectStandardOutput = true;
    psi.RedirectStandardError = true;
    psi.CreateNoWindow = true;
    p.StartInfo = psi;
    p.Start();
    var output = p.StandardOutput.ReadToEnd();
    var error = p.StandardError.ReadToEnd();
    p.WaitForExit();
    p.Dispose();
    dataFormatted = output;
    commitHash = output.Split('`')[1];

Which leaves `output` empty and results in `error` containing:

> 'git' is not recognized as an internal or external command,
> operable program or batch file.

Using [your original method](https://github.com/ArcticEcho/Phamhilator/commit/d332ba592e86c777326056ba106fff5ee3e73e02#diff-07894af82e0dda930eb7f3fdb00df54dR325) still results in an FNF.

**Comment by Vincentyification** [comment]
Why not just load up [this page](https://github.com/ArcticEcho/Phamhilator) when the program starts up and scrap the commit info from the html?

**Comment by ArcticEcho** [comment]
Yeah, I did consider that. The only problem is, the returned data may not necessarily be accurate for the local repo (which I thought was kinda the original idea).

**Comment by ProgramFOX** [comment]
@ArcticEcho Getting that error means most likely that you haven't added Git to your PATH. It works fine for me when I add Git to my PATH.

**Comment by ArcticEcho** [comment]
Erm. You didn't see anything...
