### ISSUE TITLE
Code spring cleaning + core restructuring

### ISSUE THREAD

**Issue by ArcticEcho** [ArcticEcho/Phamhilator#37]
Over the next few weeks I'll be restructuring Pham's core "ML" mechanisms, cleaning up code, etc.. As I personally feel his learning rate is too slow, and generally he's more inaccurate than I originally anticipated. So if anyone has any suggestions/ideas please feel free to say now (as I won't be doing this again for a *looong* time).

<sup>I'll keep you guys updated on Pham's new internals as I go.</sup>

**Comment by ArcticEcho** [comment]
The reset has been done (I meant to post this comment a couple of months ago).

**Comment by Vincentyification** [comment]
Will the wiki page be re-constructed?

**Comment by ArcticEcho** [comment]
Partially, yep.

**Comment by ArcticEcho** [comment]
These plans are no longer valid due to possible faults/inaccuracies that would be introduced if this issue were completed.
