### ISSUE TITLE
clean found term reports

### ISSUE THREAD

**Issue by Mooseman0** [ArcticEcho/Phamhilator#46]
Several of pham's terms are expletives. Reports such as [this one](http://chat.meta.stackexchange.com/transcript/message/2809856#2809856) include the f-bomb.

I propose that term reports can be replied to with `clean` to `******` the regex.

**Comment by Mooseman0** [comment]
Also: because of cases such as [this](http://chat.meta.stackexchange.com/transcript/message/2884600#2884600), `del` should be remapped to `clean` for term reports.

**Comment by honnza** [comment]
... or just support the del command entirely

**Comment by ArcticEcho** [comment]
Ok, what I've done is simply remap `clean` to `del` *if* `clean` fails. `del` can now delete *any* Pham message (within 2 mins of being posted, of course).
