### ISSUE TITLE
Error:  System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Vincentyification** [ArcticEcho/Phamhilator#47]
[Pham just posted this message:](http://chat.meta.stackexchange.com/transcript/message/2817086#2817086)

    `Error: 
    System.NullReferenceException: Object reference not set to an instance of an object.
       at ChatExchangeDotNet.RequestManager.GetResponse(HttpWebRequest req)
       at ChatExchangeDotNet.RequestManager.SendPOSTRequest(String uri, String content, Boolean allowAutoRedirect, String referer, String origin)
       at ChatExchangeDotNet.Room.PostMessage(String message)
       at Phamhilator.MainWindow.CheckSendReport(Post p, String messageBody, PostAnalysis info)
       at Phamhilator.MainWindow.<InitialiseSocket>b__2(Object o, MessageEventArgs message)
    
    Received message: {"action":"155-questions-active","data":"{\"siteBaseHostAddress\":\"stackoverflow.com\",\"id\":27609920,\"titleEncodedFancy\":\"Ion-nav-bar : Need help working with scopes and emit in Ionic App\",\"bodySummary\":\"So, I'm using the sidenav and I'm having trouble making my navbar dynamic. \
    \
    It used to work with this:\
    \
    &lt;ion-nav-bar ng-class=\\\"$root.color\\\"&gt;&lt;/ion-nav-bar&gt;\
    \
    controller('childStateCtrl', ...\",\"tags\":[\"angularjs\",\"angularjs-scope\",\"angular-ui-router\",\"ionic-framework\",\"ui-router\"],\"lastActivityDate\":1419321281,\"url\":\"http://stackoverflow.com/questions/27609920/ion-nav-bar-need-help-working-with-scopes-and-emit-in-ionic-app\",\"ownerUrl\":\"http://stackoverflow.com/users/3869481/ryan-usumi\",\"ownerDisplayName\":\"Ryan Usumi\",\"apiSiteParameter\":\"stackoverflow\"}"}`

I have no idea what this means, but it seems important. It probably is.

**Comment by ArcticEcho** [comment]
Well, since the last patch I haven't seen this error message again. So, *for now*, I'm going to close this.
