### ISSUE TITLE
the tp/fp acknowledging edit reverses the effects of cleaning a report

### ISSUE THREAD

**Issue by honnza** [ArcticEcho/Phamhilator#49]
steps to reproduce:

- Wait for a report from Pham. Ideally an offensive one misdetected as LQ.
- Reply with a `clean` command. This replaces the excerpt/title and username with asterisks.
- Reply with `tp` or `fp`. 

Expected behavior: In case of `tp`, "TP acknowledged" is appended to the message. Remaining parts stay cleaned. In case of `fp`, the message is struck over. Message stays replaced with asterisks underneath the strikethrough. In case of `tpa`, the message is posted in the tavern with the text and username replaced with asterisks.

Actual behavior: the effects of cleaning are completely reversed when `fp` or `tp` is used. An unclean message appears in the tavern when `tpa` is used.

Related and possibly superseeds: [Sanitize all tpa before reposting it to the Tavern #11](https://github.com/ArcticEcho/Phamhilator/issues/11)

**Comment by ArcticEcho** [comment]
I'm pretty sure this is due to CE.Net's overly-enthusiastic caching design. So, this *should* be quite easy to fix (or I at least hope so).
