### ISSUE TITLE
term reports are not replies

### ISSUE THREAD

**Issue by Mooseman0** [ArcticEcho/Phamhilator#51]
Example: http://chat.meta.stackexchange.com/transcript/message/2857920#2857920

Term reports only use `@user {report}`. They should be replies instead: `:{msgID} {report}`. The latter is the behavior for `TP/FP Acknowledged`, etc.

**Comment by ArcticEcho** [comment]
*That* specific message pings the user instead because it contains multiple (code formatted) lines, so it's not actually possible to reply.
