### ISSUE TITLE
Allow comments in reply commands

### ISSUE THREAD

**Issue by Mooseman0** [ArcticEcho/Phamhilator#55]
I propose that Pham allow for comments in reply commands. For example:

>`@Pham fp // not really spam`

The comments may be useful to provide reasoning for other users in the room, and would be completely optional.

**Comment by ArcticEcho** [comment]
Sure, this'll should be a simple matter of altering the commands' syntax regex.

**Comment by Vincentyification** [comment]
^^ Famous last words
