### ISSUE TITLE
Separate Pham's logic (to a lib) from UI

### ISSUE THREAD

**Issue by ArcticEcho** [ArcticEcho/Phamhilator#56]
As the title says, it'll be good to have Pham's logic separated to a stand-alone .dll (which'll also be useful for Gham).

**Comment by Vincentyification** [comment]
+1 also is this another step towards making this unix-compatible?

**Comment by ArcticEcho** [comment]
Thanks. Nope, but this has given me the thought of completely ditching Pham's Metro GUI (which is currently the biggest non-compatibility factor) for a simple CLI instead.

**Comment by ArcticEcho** [comment]
Actually, the more I think about it, this seems like the best approach. And, I'll be able to keep Pham all under a single .exe/branch.

**Comment by honnza** [comment]
+1 for CLI

**Comment by ArcticEcho** [comment]
Anyone have an idea for what I should call the lib/backend?

**Comment by Vincentyification** [comment]
Not me.

**Comment by ArcticEcho** [comment]
Hmm, ok. Well seeing as I'm working on it *right now* if no one has anything by tomorrow, I'll just call it Pham.Net (I know, it's *so* creative).

**Comment by Vincentyification** [comment]
Wait, how about Pham-core?

**Comment by ArcticEcho** [comment]
Nice; we have a winner! (Now why didn't I think of that?)
