### ISSUE TITLE
Pham posts an empty name on wiki posts

### ISSUE THREAD

**Issue by Mooseman0** [ArcticEcho/Phamhilator#58]
Evidence A: http://chat.meta.stackexchange.com/transcript/message/2949243#2949243

>**Low Quality A** (21.8%): [London stock exchange! http://www.theregister.co.uk/2009/11/26/lse%5Fcr...](http://serverfault.com/a/89982), by , on serverfault.com.

Pham should check for the wiki markup if the usual `user-details` is missing.

**Comment by ArcticEcho** [comment]
Turns out Pham's post fetcher (currently) can't correctly parse locked posts' author data...
