### ISSUE TITLE
Re-enable Pham's flagging capabilities

### ISSUE THREAD

**Issue by ArcticEcho** [ArcticEcho/Phamhilator#65]
Yes, the day has finally come, I'm going to re-add that good ol' flagging module (FlagExchange.Net).

**Comment by Vincentyification** [comment]
Awesome!

**Comment by Mooseman0** [comment]
FR: Only auto flag `tpa`'d posts.

**Comment by ArcticEcho** [comment]
To start, I'm planning on making a second (owner-only) for flagging posts, and depending on the  its success (and how well it is accepted by the community) I'll then see about implementing the auto flagging part.

**Comment by Mooseman0** [comment]
+1

**Comment by Vincentyification** [comment]
![](http://i.gyazo.com/a33ed6ddc3896807d588962873522a53.png)

**Comment by ArcticEcho** [comment]
xD

**Comment by ArcticEcho** [comment]
The core functions have now been added (they have yet to be exposed though).
