### ISSUE TITLE
Add an indication to a report whether that report comes from a TPA or an auto-term

### ISSUE THREAD

**Issue by honnza** [ArcticEcho/Phamhilator#66]
Currenly the reports look like this:

> Low Quality A (22.6%): [Aaaabbbbccccddddeeeeffffgggghh](http://example.com), by [jay r. t. Roll](http://example.com), on [apple.stackexchange.com](http://example.com)

This is the same for auto-reports as well as reports from us. I propose this form for announced reports:

> Low Quality A ([confirmed](http://example.com)): [Aaaabbbbccccddddeeeeffffgggghh](http://example.com), by [jay r. t. Roll](http://example.com), on [apple.stackexchange.com](http://example.com)

(or another word; the key part is that we don't really need the percentage anymore - and a blame link would be nice)

**Comment by ArcticEcho** [comment]
+1 I like the blame link idea.

**Comment by Mooseman0** [comment]
Perhaps it'd be a good idea to *italicize* or **bold** the `confirmed` link?

**Comment by Vincentyification** [comment]
It also doesn't hurt to directly add the TPA'er's name within the report itself. [At least Blaze does it](http://chat.stackexchange.com/transcript/message/19833639#19833639), and it's not bad:

![](http://gyazo.com/968beb7494672a86f16adb35f645a235.png)

**Comment by ArcticEcho** [comment]
Sure, sounds good.

**Comment by ArcticEcho** [comment]
So just to recap; TPA'd reports will now look like this:

> **Low Quality A** (by [TPA'er's name](http:/)): [Aaaabbbbccccddddeeeeffffgggghh](htttp://), by [jay r. t. Roll](http://), on `apple.stackexchange.com`.

**Comment by Mooseman0** [comment]
1. Is {TPA'er's name} to be italicized? (The "by" should also be italicized.)
 2. I apologize if this ought to be a second FR, but can we optionally specify (e.g., **tpa naa** or **tpa too-broad**) a reason, besides the generic **Very Low Quality**?

**Comment by ArcticEcho** [comment]
1. I didn't plan on italicising any of it.
2. See #39.

**Comment by Mooseman0** [comment]
Sounds good.
