### ISSUE TITLE
TP acknowledgements seem to stack.

### ISSUE THREAD

**Issue by honnza** [ArcticEcho/Phamhilator#67]
Steps to reproduce:

- have Pham post a report
- TP the report. Pham will acknowledge the TP.
- TPA the report. Pham will acknowledge the TPA, as well as the TP.

The resulting state is as such:

> **Spam Q** (66.7%): [One Of The Most Cleaver Option For Weight Loss](http://example.com), by [□ danayotte](http://example.com), on [askubuntu.com](http://example.com) **TP Acknowledged TPA Acknowledged.**

Instead, even if a post gets TP'd multiple times, only one acknowledgement should be posted (TPA if announced, TP otherwise)

Also see: #68

**Comment by honnza** [comment]
Also, the tavern announcement will have the TP acknowledgement posted as a part of the message.

**Comment by ArcticEcho** [comment]
Good catch. Only acknowledging the first command should "kill two birds with one stone." Let's just hope no one accidentally FP/TPs something they shouldn't.

**Comment by honnza** [comment]
Also, FP'ing a report twice will result in a failed attempt to strike the report twice (post is surrounded with six dashes on each side)
