### ISSUE TITLE
Debounce the effects of FP/TP

### ISSUE THREAD

**Issue by honnza** [ArcticEcho/Phamhilator#68]
Followup from #67, but extends past the 2-minute window in which messages can be edited.

Ideally, the following states should be present:
Fresh: initial state. Reactions to FP/TP/TPA should be as they are currently, plus transitions to FP'd, TP'd or TPA'd state as accordingly.
FP'd: Additional FPs are ignored. TP/TPA should undo the effects of FP, then proceed as usual and transition to the corresponding state (except if less than 5 seconds passed since the last transition from TPA'd?).
TP'd: Additional TPs are ignored. TPA should announce the report (without the TP acknowledgement) and transition to the TPA'd state. Do not adjust the term scores. FP should undo the effects of TP, then proceed as usual and transition to the FP'd state.
TPA'd: Additional TPs and TPAs are ignored. FP should undo the effects of TP, delete the report, apply the term change effects as usual and transition to the FP'd state. If deleting fails, do not repost the announcement ever again.

If undoing term score changes is impossible / impractical, this simplifies to "ignore all responses past the first one, except:"

- TPA after a TP or FP still announces the report. Do not announce twice. The announcement should not have a "TP acknowledged" appended to it. The announcement should not be struck over.
- FP after a TPA deletes the announcement. If deletion is successful, further TPAs will repost it (possibly only if some time will have passed since the FP - 5 seconds?).

**Comment by Mooseman0** [comment]
I got [this](http://chat.meta.stackexchange.com/transcript/message/3007542#3007542) after stacking `tp fp tp`:

---Low Quality Q (15.6%): How to check whether record exists in Core Data? If yes don't add another. Swift, by □ Maselko, on stackoverflow.com ***TP Acknowledged.***-- ***TP Acknowledged.***

**Comment by honnza** [comment]
@Mooseman0 I'd say this is a part of the bug report... (maybe I should have posted these as a single issue?)

**Comment by Mooseman0** [comment]
@honnza I think it's all the same bug. Pham needs to pull from the cache when editing reports rather than relying on the current message contents.

**Comment by honnza** [comment]
I'd say it's a design tarpit that Pham relies on the current message state _at all_. It should generate the report each time anew.

**Comment by ArcticEcho** [comment]
I fully agree. Confession time: when I first moved ack'ing TPs/FPs to just editing the report I thought "eh, wth. I'll just rely on the message content" and edit that instead. So, yeah, I should've regenerated reports from the cached data instead, my bad.
