### ISSUE TITLE
Subscribing to filters

### ISSUE THREAD

**Issue by Unihedro** [ArcticEcho/Phamhilator#8]
Based on [this conversation](http://chat.meta.stackexchange.com/transcript/message/2405316#2405316), users can subscribe to specific filters (Low Quality A, Spam, etc) and be pinged when a post is caught and they were within the room.

**Comment by ArcticEcho** [comment]
I think it'll be best to implement this after Pham's accuracy has increased. Otherwise he could end up pinging people FP reports.

**Comment by ArcticEcho** [comment]
Having seen how the Charcoal team have already done this, I doubt this FR will still be of great use. I'll close this for now.
